language: php
php:
    - 7.2
    - nightly
before_install:
    - git clone -b stable https://github.com/jedisct1/libsodium.git
    - cd libsodium && sudo ./configure && sudo make check && sudo make install && cd ..
install:
    - pecl install libsodium
    - echo "extension=sodium.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script: composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
