language: php
php:
    - 7.2
    - nightly
before_install:
    - sudo add-apt-repository ppa:ondrej/php -y
    - sudo apt-get update -q
    - sudo apt-get install libsodium-dev -y
before_script:
    - pecl install libsodium
    - composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
